name: leod
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip:
    - opencv-python
    - matplotlib
    - pandas
    - pillow
    - torchvision
    - ultralytics
    - albumentations
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - tqdm
    - tensorboard
    - wandb
    - yacs
    - pycocotools
    - fvcore
    - iopath
    - yapf
    - black
    - flake8
    - pytest
    - absl-py
    - addict
    - aiohttp
    - aiosignal
    - antlr4-python3-runtime
    - anyio
    - appdirs
    - arrow
    - asttokens
    - async-timeout
    - attrs
    - backcall
    - bbox-visualizer
    - beautifulsoup4
    - blessed
    - cachetools
    - click
    - clip
    - cloudpickle
    - comm
    - configargparse
    - contourpy
    - croniter
    - cycler
    - dash
    - dash-core-components
    - dash-html-components
    - dash-table
    - dateutils
    - debugpy
    - decorator
    - deepdiff
    - docker-pycreds
    - einops
    - exceptiongroup
    - executing
    - fastapi
    - fastjsonschema
    - filterpy
    - fire
    - flask
    - fonttools
    - frozenlist
    - fsspec
    - ftfy
    - fvcore
    - gdown
    - gitdb
    - gitpython
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - h11
    - h5py
    - hdf5plugin
    - hydra-core
    - imageio
    - imageio-ffmpeg
    - importlib-metadata
    - importlib-resources
    - inquirer
    - iopath
    - ipykernel
    - ipython
    - ipywidgets
    - itsdangerous
    - jedi
    - joblib
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyterlab-widgets
    - kiwisolver
    - lap
    - lazy-loader
    - lightning-cloud
    - lightning-utilities
    - llvmlite
    - lpips
    - markdown
    - markdown-it-py
    - matplotlib-inline
    - mdurl
    - moviepy
    - multidict
    - mypy-extensions
    - nbformat
    - nest-asyncio
    - nose
    - numba
    - oauthlib
    - omegaconf
    - open3d
    - ordered-set
    - packaging
    - parso
    - pathspec
    - pathtools
    - pexpect
    - phyre
    - pickleshare
    - platformdirs
    - plotly
    - portalocker
    - prettytable
    - proglog
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - pure-eval
    - pyasn1
    - pyasn1-modules
    - pycocotools
    - pydantic
    - pygments
    - pyjwt
    - pyparsing
    - pyquaternion
    - pyrsistent
    - python-dateutil
    - python-editor
    - python-multipart
    - pytorch-lightning
    - pytz
    - pywavelets
    - pyyaml
    - pyzmq
    - readchar
    - regex
    - requests-oauthlib
    - rich
    - rsa
    - sentry-sdk
    - setproctitle
    - smmap
    - sniffio
    - soupsieve
    - stack-data
    - starlette
    - starsessions
    - strenum
    - tabulate
    - tenacity
    - tensorboard-data-server
    - tensorboardx
    - termcolor
    - threadpoolctl
    - thrift
    - tifffile
    - tomli
    - torchdata
    - torchmetrics
    - tornado
    - traitlets
    - ultralytics
    - uvicorn
    - wandb
    - wcwidth
    - websocket-client
    - websockets
    - werkzeug
    - widgetsnbextension
    - yacs
    - yarl
    - zipp